//
//  NavigationStoryboardExtensions.swift
//
//  This file is automatically generated; do not modify.
//

import UIKit

private let sharedStoryboardInstance = UIStoryboard(name: "Navigation", bundle: nil)

private class InitializeBlockObject {
    
    let block: (UIViewController -> Void)
    
    init(block: (UIViewController -> Void)) {
        self.block = block
    }
    
}

extension MenuViewController {
    
    final class func instantiateViewControllerFromStoryboard(@noescape initialize: ((menuViewController: MenuViewController) -> Void) = {_ in}) -> MenuViewController {
        let viewController = sharedStoryboardInstance.instantiateViewControllerWithIdentifier("MenuViewController") as! MenuViewController
        initialize(menuViewController: viewController)
        return viewController
    }
    
    final class func instantiateNavigationControllerFromStoryboard(@noescape initialize: ((menuViewController: MenuViewController) -> Void) = {_ in}) -> UINavigationController {
        let navigationController = sharedStoryboardInstance.instantiateViewControllerWithIdentifier("MenuNavigationController") as! UINavigationController
        let viewController = navigationController.viewControllers.first as! MenuViewController
        initialize(menuViewController: viewController)
        return navigationController
    }
    
    // Segues
    
    func handleSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let initializeBlockObject = sender as? InitializeBlockObject {
            initializeBlockObject.block(segue.destinationViewController)
        }
    }
    
}

extension WelcomeViewController {
    
    final class func instantiateViewControllerFromStoryboard(@noescape initialize: ((welcomeViewController: WelcomeViewController) -> Void) = {_ in}) -> WelcomeViewController {
        let viewController = sharedStoryboardInstance.instantiateViewControllerWithIdentifier("WelcomeViewController") as! WelcomeViewController
        initialize(welcomeViewController: viewController)
        return viewController
    }
    
    final class func instantiateNavigationControllerFromStoryboard(@noescape initialize: ((welcomeViewController: WelcomeViewController) -> Void) = {_ in}) -> UINavigationController {
        let navigationController = sharedStoryboardInstance.instantiateViewControllerWithIdentifier("WelcomeNavigationController") as! UINavigationController
        let viewController = navigationController.viewControllers.first as! WelcomeViewController
        initialize(welcomeViewController: viewController)
        return navigationController
    }
    
    // Segues
    
    enum SegueIdentifier: String {
        case ShowMenu = "ShowMenu"
    }
    
    func handleSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let initializeBlockObject = sender as? InitializeBlockObject {
            initializeBlockObject.block(segue.destinationViewController)
        }
    }
    
    final func performShowMenuSegue(initialize: ((MenuViewController) -> Void) = {_ in}) {
        let initializeBlock = InitializeBlockObject() {
            let navigationController = $0 as! UINavigationController
            let viewController = navigationController.viewControllers.first as! MenuViewController
            initialize(viewController)
        }
        performSegueWithIdentifier(SegueIdentifier.ShowMenu.rawValue, sender: initializeBlock)
    }
    
}
