//
//  UIImageExtensions.swift
//
//  This file is automatically generated; do not modify.
//

import UIKit

fileprivate let bundle: Bundle = {
    class Object: NSObject { }
    return Bundle(for: Object.self)
}()

fileprivate extension UIImage {
    
    convenience init!(identifier: ImageAssetIdentifier, compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) {
        self.init(named: identifier.rawValue, in: bundle, compatibleWith: nil)
    }
    
}

enum ImageAssetIdentifier: String {
    
    case apple = "apple"
    case bigApple = "big_apple"
    case largeApple = "large-apple"
    case redApple = "redApple"
    case smallApple = "small apple"
    
}

extension UIImage {
    
    static var apple: UIImage {
        return UIImage(identifier: .apple)
    }
    
    static var bigApple: UIImage {
        return UIImage(identifier: .bigApple)
    }
    
    static var largeApple: UIImage {
        return UIImage(identifier: .largeApple)
    }
    
    static var redApple: UIImage {
        return UIImage(identifier: .redApple)
    }
    
    static var smallApple: UIImage {
        return UIImage(identifier: .smallApple)
    }
    
}