ios:
  target: 13.0
  sdk: 14.5

symbols-collection:
  name: Example App

symbols:
- a.book.closed
- 14.square.fill
- case
- case.fill
- character.book.closed
- chevron.down
- chevron.up
- die.face.1
- die.face.4
- infinity.circle.fill
- minus.circle.fill
- person
- person.2
- plus.circle.fill
- return
- repeat
- repeat.circle

localizable:
  base: en
  arguments:
    "Days since last injury: %@": [numberOfDays]
    COOKIE_COUNT: [cookies]
    greetings: [firstName, lastName]
