//
// Copyright (c) 2019 Nathan E. Walczak
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

import Foundation

let BlackboardImageSwiftSourceTestData = """
//
//  UIImageExtensions.swift
//
//  This file is automatically generated; do not modify.
//

import UIKit

fileprivate let bundle: Bundle = {
    class Object: NSObject { }
    return Bundle(for: Object.self)
}()

fileprivate extension UIImage {
    
    convenience init!(identifier: ImageAssetIdentifier, compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) {
        self.init(named: identifier.rawValue, in: bundle, compatibleWith: nil)
    }
    
}

enum ImageAssetIdentifier: String {
    
    case apple = "apple"
    case bigApple = "big_apple"
    case everythingApple = "everything--apple"
    case largeApple = "large-apple"
    case redApple = "RedApple"
    case smallApple = "small apple"
    
}

extension UIImage {
    
    static var apple: UIImage {
        return UIImage(identifier: .apple)
    }
    
    static var bigApple: UIImage {
        return UIImage(identifier: .bigApple)
    }
    
    static var everythingApple: UIImage {
        return UIImage(identifier: .everythingApple)
    }
    
    static var largeApple: UIImage {
        return UIImage(identifier: .largeApple)
    }
    
    static var redApple: UIImage {
        return UIImage(identifier: .redApple)
    }
    
    static var smallApple: UIImage {
        return UIImage(identifier: .smallApple)
    }
    
}

"""
