//
// Copyright (c) 2019 Nathan E. Walczak
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

import Foundation

let BlackboardCGColorSwiftSource = """
//
//  CGColor.blackboard.swift
//
//  This file is automatically generated; do not modify.
//

import UIKit

extension CGColor {
    
    static var absoluteZero: CGColor {
        return UIColor.absoluteZero.cgColor
    }
    
    static var bisque: CGColor {
        return UIColor.bisque.cgColor
    }
    
    static var black: CGColor {
        return UIColor.black.cgColor
    }
    
    static var blue: CGColor {
        return UIColor.blue.cgColor
    }
    
    static var brown: CGColor {
        return UIColor.brown.cgColor
    }
    
    static var charcoal: CGColor {
        return UIColor.charcoal.cgColor
    }
    
    static var clear: CGColor {
        return UIColor.clear.cgColor
    }
    
    static var cyan: CGColor {
        return UIColor.cyan.cgColor
    }
    
    static var darkGray: CGColor {
        return UIColor.darkGray.cgColor
    }
    
    static var darkOliveGreen: CGColor {
        return UIColor.darkOliveGreen.cgColor
    }
    
    static var desire: CGColor {
        return UIColor.desire.cgColor
    }
    
    static var emerald: CGColor {
        return UIColor.emerald.cgColor
    }
    
    static var firebrick: CGColor {
        return UIColor.firebrick.cgColor
    }
    
    static var fluorescentBlizzardBlue: CGColor {
        return UIColor.fluorescentBlizzardBlue.cgColor
    }
    
    static var fluorescentMagicMint: CGColor {
        return UIColor.fluorescentMagicMint.cgColor
    }
    
    static var fluorescentRadicalRed: CGColor {
        return UIColor.fluorescentRadicalRed.cgColor
    }
    
    static var gray: CGColor {
        return UIColor.gray.cgColor
    }
    
    static var green: CGColor {
        return UIColor.green.cgColor
    }
    
    static var lightGray: CGColor {
        return UIColor.lightGray.cgColor
    }
    
    static var magenta: CGColor {
        return UIColor.magenta.cgColor
    }
    
    static var maroon: CGColor {
        return UIColor.maroon.cgColor
    }
    
    static var night: CGColor {
        return UIColor.night.cgColor
    }
    
    static var orange: CGColor {
        return UIColor.orange.cgColor
    }
    
    static var purple: CGColor {
        return UIColor.purple.cgColor
    }
    
    static var red: CGColor {
        return UIColor.red.cgColor
    }
    
    static var white: CGColor {
        return UIColor.white.cgColor
    }
    
    static var yellow: CGColor {
        return UIColor.yellow.cgColor
    }
    
}

"""
