//
// Copyright (c) 2022 Nathan E. Walczak
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

import Foundation

class SwiftSource {
    private var lines: [(indentLevel: Int, line: String)] = []

    @discardableResult
    func append(_ line: String = "", indentLevel: Int? = nil) -> Self {
        let indentLevel = indentLevel ?? self.indentLevel

        if line.isEmpty, line == lines.last?.line {
            return self // don't allow multiple blank lines
        }

        if insideCommentBlock {
            for comment in line.components(separatedBy: CharacterSet.newlines) {
                lines.append((indentLevel, "/// \(comment)"))
            }
        } else {
            lines.append((indentLevel, line))
        }

        return self
    }

    @discardableResult
    func append(_ line: String, block: () -> Void) -> Self {
        append("\(line) {")

        let initialCount = lines.count

        indent(block)

        if lines.count - initialCount == 1, lines.last?.line.isEmpty == true {
            lines.removeLast()
        }

        removeLastBlankLine()

        append("}")

        return self
    }

    func removeLastBlankLine() {
        if lines.last?.line.trimmingWhitespaceCharacters.isEmpty == true {
            lines.removeLast()
        }
    }

    var source: String {
        var source: [String] = []

        var indentLevel = 0
        var indent = ""

        for entry in lines {
            if indentLevel != entry.indentLevel {
                indentLevel = entry.indentLevel
                indent = ""
                for _ in 0 ..< indentLevel {
                    indent.append("    ")
                }
            }

            let line = "\(indent)\(entry.line)"
                .trimmingTrailingWhitespaceCharacters

            if line.trimmingWhitespaceCharacters == "}", let last = source.last, last.suffix(1) == "{" {
                source.removeLast()
                source.append("\(last)}")
            } else {
                source.append(line)
            }
        }

        return source.joined(separator: "\n")
    }

    // MARK: Indent Level

    var indentLevel = 0

    func indent() {
        indentLevel += 1
    }

    func unindent() {
        indentLevel = max(0, indentLevel - 1)
    }

    func indent(_ block: () -> Void) {
        indent()
        block()
        unindent()
    }

    // MARK: Comment Block

    var insideCommentBlock = false
}

extension SwiftSource {
    func append(source: String) -> Self {
        source.components(separatedBy: CharacterSet.newlines)
            .forEach { append($0) }
        return self
    }

    func commentBlock(block: () -> Void) {
        insideCommentBlock = true

        block()

        insideCommentBlock = false
    }

    func appendHeading(
        filename: String,
        modules: [String] = [],
        publicModules: [String] = [],
        includeBundle: Bool = false
    ) {
        append("//")
        append("//  \(filename)")
        append("//")
        append("//  This file is automatically generated; do not modify.")
        append("//")
        append()

        for module in modules {
            append("import \(module)")
        }

        append()

        if !publicModules.isEmpty {
            append("#if hasFeature(InternalImportsByDefault)")
            indent {
                for module in publicModules {
                    append("public import \(module)")
                }
            }
            append("#else")
            indent {
                for module in publicModules {
                    append("import \(module)")
                }
            }
            append("#endif")
        }

        append()

        if includeBundle {
            append("private let bundle: Bundle = {")
            indent {
                append("#if SWIFT_PACKAGE")
                indent {
                    append("Bundle.module")
                }
                append("#else")
                indent {
                    append("class Object: NSObject {}")
                    append("return Bundle(for: Object.self)")
                }
                append("#endif")
            }
            append("}()")
            append()
        }
    }

    func appendAssetItems<Asset>(_ assetItems: [AssetItem<Asset>], block: (_ asset: Asset) -> Void) {
        for asset in assetItems {
            switch asset {
            case let .asset(asset):
                block(asset)
            case let .namespace(namespace, assets):
                let namespace = Naming.lastNamespaceName(from: namespace)
                append("enum \(namespace)") {
                    appendAssetItems(assets, block: block)
                }
                append()
            }
        }
    }
}
